set(public_headers
    animate.h
    annotate.h
    artifact.h
    attribute.h
    blob.h
    cache-view.h
    cache.h
    channel.h
    cipher.h
    client.h
    coder.h
    color.h
    colormap.h
    colorspace.h
    compare.h
    composite.h
    compress.h
    configure.h
    constitute.h
    decorate.h
    delegate.h
    deprecate.h
    display.h
    distort.h
    distribute-cache.h
    draw.h
    effect.h
    enhance.h
    exception.h
    feature.h
    fourier.h
    fx.h
    gem.h
    geometry.h
    histogram.h
    identify.h
    image-view.h
    image.h
    layer.h
    linked-list.h
    list.h
    locale_.h
    log.h
    magic.h
    magick-config.h
    magick-type.h
    magick.h
    MagickCore.h
    matrix.h
    memory_.h
    method-attribute.h
    methods.h
    mime.h
    module.h
    monitor.h
    montage.h
    morphology.h
    nt-base.h
    opencl.h
    option.h
    paint.h
    pixel-accessor.h
    pixel.h
    policy.h
    prepress.h
    profile.h
    property.h
    quantize.h
    quantum.h
    random_.h
    registry.h
    resample.h
    resize.h
    resource_.h
    segment.h
    semaphore.h
    shear.h
    signature.h
    splay-tree.h
    statistic.h
    stream.h
    string_.h
    studio.h
    threshold.h
    timer.h
    token.h
    transform.h
    type.h
    utility.h
    version.h
    vision.h
    widget.h
    xml-tree.h
    xwindow.h
    
    # Generated files
    ${CMAKE_CURRENT_BINARY_DIR}/version.h
    ${CMAKE_CURRENT_BINARY_DIR}/magick-baseconfig.h
)

set(private_headers
    accelerate-kernels-private.h
    accelerate-private.h
    animate-private.h
    annotate-private.h
    blob-private.h
    cache-private.h
    cache-private.h
    coder-private.h
    color-private.h
    color-private.h
    colormap-private.h
    colorspace-private.h
    composite-private.h
    configure-private.h
    constitute-private.h
    delegate-private.h
    delegate-private.h
    display-private.h
    distribute-cache-private.h
    draw-private.h
    exception-private.h
    fx-private.h
    gem-private.h
    image-private.h
    locale-private.h
    log-private.h
    magic-private.h
    magick-private.h
    matrix-private.h
    memory-private.h
    methods-private.h
    mime-private.h
    mime-private.h
    module-private.h
    monitor-private.h
    morphology-private.h
    nt-base.h
    nt-feature.h
    opencl-private.h
    option-private.h
    pixel-private.h
    policy-private.h
    profile-private.h
    quantum-private.h
    random-private.h
    random_-private.h
    registry-private.h
    resample-private.h
    resize-private.h
    resource-private.h
    resource-private.h
    semaphore-private.h
    semaphore-private.h
    signature-private.h
    static.h
    stream-private.h
    string-private.h
    thread-private.h
    thread_.h
    token-private.h
    transform-private.h
    type-private.h
    utility-private.h
    version-private.h
    widget-private.h
    xml-tree-private.h
    xwindow-private.h
)

set(source_files
    accelerate.c
    animate.c
    annotate.c
    artifact.c
    attribute.c
    blob.c
    cache-view.c
    cache.c
    channel.c
    cipher.c
    client.c
    coder.c
    color.c
    colormap.c
    colorspace.c
    compare.c
    composite.c
    compress.c
    configure.c
    constitute.c
    decorate.c
    delegate.c
    deprecate.c
    display.c
    distort.c
    distribute-cache.c
    draw.c
    effect.c
    enhance.c
    exception.c
    feature.c
    fourier.c
    fx.c
    gem.c
    geometry.c
    histogram.c
    identify.c
    image-view.c
    image.c
    layer.c
    linked-list.c
    list.c
    locale.c
    log.c
    magic.c
    magick.c
    matrix.c
    memory.c
    mime.c
    module.c
    monitor.c
    montage.c
    morphology.c
    nt-base.c
    nt-feature.c
    opencl.c
    option.c
    paint.c
    pixel.c
    policy.c
    prepress.c
    profile.c
    property.c
    quantize.c
    quantum-export.c
    quantum-import.c
    quantum.c
    random.c
    registry.c
    resample.c
    resize.c
    resource.c
    segment.c
    semaphore.c
    shear.c
    signature.c
    splay-tree.c
    static.c
    statistic.c
    stream.c
    string.c
    thread.c
    threshold.c
    timer.c
    token.c
    transform.c
    type.c
    utility.c
    version.c
    vision.c
    vms.c
    widget.c
    xml-tree.c
    xwindow.c
)
